version: '3.9'

services:

  lumen:

    build: .
    
    ports:
      - 8000:8000
    volumes:
      - .:/app

    command: >-

      bash -c "
          composer dump-autoload;
          composer install;
          php artisan migrate;
          php -S 0.0.0.0:8000 -t public;"

    networks:
      - backend

    depends_on:
      - db

  db:
    image: rapidfort/mysql:latest
    container_name: mysql
    restart: always
    environment:

      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=api

    networks:
      - backend

networks:

  backend:

    driver: bridge
